### ISSUE TITLE
After last release, build failes

### ISSUE THREAD

**Issue by slavikdenis** [suwu150/react-native-tree-select#16]
Version:
`"react-native-tree-select": "^2.0.8"`

Error:
```
Loading dependency graph...(node:13092) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: F:\repos\inqool\metro\mobile\node_modules\react-native-tree-select\node_modules\react-native\package.json collides with F:\repos\inqool\metro\mobile\node_modules\reac
t-native\package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (F:\repos\inqool\metro\mobile\node_modules\jest-haste-map\build\index.js:569:17)
    at workerReply (F:\repos\inqool\metro\mobile\node_modules\jest-haste-map\build\index.js:641:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:13092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by r
ejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proce
ss with a non-zero exit code.
(node:13092) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: F:\repos\inqool\metro\mobile\node_modules\react-native-tree-select\node_modules\react-native\package.json collides with F:\repos\inqool\metro\mobile\node_modules\reac
t-native\package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (F:\repos\inqool\metro\mobile\node_modules\jest-haste-map\build\index.js:569:17)
    at workerReply (F:\repos\inqool\metro\mobile\node_modules\jest-haste-map\build\index.js:641:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:13092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by r
ejecting a promise which was not handled with .catch(). (rejection id: 3)
::ffff:127.0.0.1 - - [02/Sep/2019:09:35:11 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 825 "-" "okhttp/3.12.1"
Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: F:\repos\inqool\metro\mobile\node_modules\react-native-tree-select\node_modules\react-native\package.json collides with F:\repos\inqool\metro\mobile\node_modules\reac
t-native\package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (F:\repos\inqool\metro\mobile\node_modules\jest-haste-map\build\index.js:569:17)
    at workerReply (F:\repos\inqool\metro\mobile\node_modules\jest-haste-map\build\index.js:641:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

```

**Comment by suwu150** [comment]
@slavikdenis  What is the version of react-native?

**Comment by slavikdenis** [comment]
`"react-native": "0.59.10"`

**Comment by suwu150** [comment]
Update the component to the latest version 2.0.9.

**Comment by slavikdenis** [comment]
Works great, thanks
