### ISSUE TITLE
安装后启动时error: bundling failed: Error: jest-haste-map: 

### ISSUE THREAD

**Issue by suwu150** [suwu150/react-native-tree-select#17]
```
 > 0.57.8版本rn装这个会报错
 error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
 Duplicate module name: react-native Paths: d:\workspace\RN\appdemo\node_modules\react-native-tree-select\node_modules\react-native\package.json collides with d:\workspace\RN\appdemo\node_modules\react-native\package.json This error is caused by a @providesModule declaration with the same name across two different files. at setModule (d:\workspace\RN\appdemo\node_modules\metro\node_modules\jest-haste-map\build\index.js:462:17) at workerReply (d:\workspace\RN\appdemo\node_modules\metro\node_modules\jest-haste-map\build\index.js:512:9) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by suwu150** [comment]
解决方案:更新至最新版本2.0.9.
